/**
 * AUTO-GENERATED by scripts/syncCloudinaryMedia.ts — do not edit by hand.
 * Re-run: npm run sync:media --prefix backend
 */
export const CLOUD_MEDIA: Record<string, string> = {
  "/images/agent-robo-cute.png": "https://res.cloudinary.com/dq96gflxv/image/upload/v1789196509/VISION-Y/branding/agent-robo-cute.jpg",
  "/images/agent-robo.png": "https://res.cloudinary.com/dq96gflxv/image/upload/v1789196510/VISION-Y/branding/agent-robo.jpg",
  "/images/avatars/default.svg": "https://res.cloudinary.com/dq96gflxv/image/upload/v1789196511/VISION-Y/avatars/placeholders/default.svg",
  "/images/avatars/faculty-01.svg": "https://res.cloudinary.com/dq96gflxv/image/upload/v1789196512/VISION-Y/avatars/placeholders/faculty-01.svg",
  "/images/avatars/faculty-02.svg": "https://res.cloudinary.com/dq96gflxv/image/upload/v1789196515/VISION-Y/avatars/placeholders/faculty-02.svg",
  "/images/avatars/faculty-03.svg": "https://res.cloudinary.com/dq96gflxv/image/upload/v1789196516/VISION-Y/avatars/placeholders/faculty-03.svg",
  "/images/avatars/faculty-04.svg": "https://res.cloudinary.com/dq96gflxv/image/upload/v1789196518/VISION-Y/avatars/placeholders/faculty-04.svg",
  "/images/avatars/faculty-05.svg": "https://res.cloudinary.com/dq96gflxv/image/upload/v1789196519/VISION-Y/avatars/placeholders/faculty-05.svg",
  "/images/avatars/faculty-06.svg": "https://res.cloudinary.com/dq96gflxv/image/upload/v1789196521/VISION-Y/avatars/placeholders/faculty-06.svg",
  "/images/avatars/faculty-07.svg": "https://res.cloudinary.com/dq96gflxv/image/upload/v1789196524/VISION-Y/avatars/placeholders/faculty-07.svg",
  "/images/avatars/faculty-08.svg": "https://res.cloudinary.com/dq96gflxv/image/upload/v1789196525/VISION-Y/avatars/placeholders/faculty-08.svg",
  "/images/avatars/faculty-09.svg": "https://res.cloudinary.com/dq96gflxv/image/upload/v1789196527/VISION-Y/avatars/placeholders/faculty-09.svg",
  "/images/avatars/faculty-10.svg": "https://res.cloudinary.com/dq96gflxv/image/upload/v1789196529/VISION-Y/avatars/placeholders/faculty-10.svg",
  "/images/avatars/student-01.svg": "https://res.cloudinary.com/dq96gflxv/image/upload/v1789196530/VISION-Y/avatars/placeholders/student-01.svg",
  "/images/avatars/student-02.svg": "https://res.cloudinary.com/dq96gflxv/image/upload/v1789196532/VISION-Y/avatars/placeholders/student-02.svg",
  "/images/avatars/student-03.svg": "https://res.cloudinary.com/dq96gflxv/image/upload/v1789196533/VISION-Y/avatars/placeholders/student-03.svg",
  "/images/avatars/student-04.svg": "https://res.cloudinary.com/dq96gflxv/image/upload/v1789196535/VISION-Y/avatars/placeholders/student-04.svg",
  "/images/avatars/student-05.svg": "https://res.cloudinary.com/dq96gflxv/image/upload/v1789196536/VISION-Y/avatars/placeholders/student-05.svg",
  "/images/avatars/student-06.svg": "https://res.cloudinary.com/dq96gflxv/image/upload/v1789196539/VISION-Y/avatars/placeholders/student-06.svg",
  "/images/avatars/student-07.svg": "https://res.cloudinary.com/dq96gflxv/image/upload/v1789196544/VISION-Y/avatars/placeholders/student-07.svg",
  "/images/avatars/student-08.svg": "https://res.cloudinary.com/dq96gflxv/image/upload/v1789196547/VISION-Y/avatars/placeholders/student-08.svg",
  "/images/avatars/student-09.svg": "https://res.cloudinary.com/dq96gflxv/image/upload/v1789196549/VISION-Y/avatars/placeholders/student-09.svg",
  "/images/avatars/student-10.svg": "https://res.cloudinary.com/dq96gflxv/image/upload/v1789196550/VISION-Y/avatars/placeholders/student-10.svg",
  "/images/avatars/students/ananya.png": "https://res.cloudinary.com/dq96gflxv/image/upload/v1789196552/VISION-Y/students/ananya.png",
  "/images/avatars/students/arjun.png": "https://res.cloudinary.com/dq96gflxv/image/upload/v1789196553/VISION-Y/students/arjun.png",
  "/images/avatars/students/asha.png": "https://res.cloudinary.com/dq96gflxv/image/upload/v1789196554/VISION-Y/students/asha.png",
  "/images/avatars/students/divya.png": "https://res.cloudinary.com/dq96gflxv/image/upload/v1789196554/VISION-Y/students/divya.png",
  "/images/avatars/students/karthik.png": "https://res.cloudinary.com/dq96gflxv/image/upload/v1789196555/VISION-Y/students/karthik.png",
  "/images/avatars/students/meera.png": "https://res.cloudinary.com/dq96gflxv/image/upload/v1789196556/VISION-Y/students/meera.png",
  "/images/avatars/students/nikhil.png": "https://res.cloudinary.com/dq96gflxv/image/upload/v1789196559/VISION-Y/students/nikhil.png",
  "/images/avatars/students/rahul.png": "https://res.cloudinary.com/dq96gflxv/image/upload/v1789196560/VISION-Y/students/rahul.png",
  "/images/avatars/students/sneha.png": "https://res.cloudinary.com/dq96gflxv/image/upload/v1789196562/VISION-Y/students/sneha.png",
  "/images/avatars/students/vikram.png": "https://res.cloudinary.com/dq96gflxv/image/upload/v1789196563/VISION-Y/students/vikram.png",
  "/images/faculty/balu.jpg": "https://res.cloudinary.com/dq96gflxv/image/upload/v1789196563/VISION-Y/faculty/balu.jpg",
  "/images/faculty/jhansi.jpg": "https://res.cloudinary.com/dq96gflxv/image/upload/v1789196564/VISION-Y/faculty/jhansi.jpg",
  "/images/faculty/parimala.jpg": "https://res.cloudinary.com/dq96gflxv/image/upload/v1789196565/VISION-Y/faculty/parimala.jpg",
  "/images/faculty/prathap.jpg": "https://res.cloudinary.com/dq96gflxv/image/upload/v1789196567/VISION-Y/faculty/prathap.jpg",
  "/images/faculty/profilepic01702.png": "https://res.cloudinary.com/dq96gflxv/image/upload/v1789196568/VISION-Y/faculty/profilepic01702.png",
  "/images/faculty/profilepic01988.JPG": "https://res.cloudinary.com/dq96gflxv/image/upload/v1789196569/VISION-Y/faculty/profilepic01988.jpg",
  "/images/faculty/profilepic01988.jpg": "https://res.cloudinary.com/dq96gflxv/image/upload/v1789196569/VISION-Y/faculty/profilepic01988.jpg",
  "/images/faculty/profilepic02181.JPG": "https://res.cloudinary.com/dq96gflxv/image/upload/v1789196571/VISION-Y/faculty/profilepic02181.jpg",
  "/images/faculty/profilepic02181.jpg": "https://res.cloudinary.com/dq96gflxv/image/upload/v1789196571/VISION-Y/faculty/profilepic02181.jpg",
  "/images/faculty/profilepic02194.JPG": "https://res.cloudinary.com/dq96gflxv/image/upload/v1789196572/VISION-Y/faculty/profilepic02194.jpg",
  "/images/faculty/profilepic02194.jpg": "https://res.cloudinary.com/dq96gflxv/image/upload/v1789196572/VISION-Y/faculty/profilepic02194.jpg",
  "/images/faculty/profilepic02396.jpg": "https://res.cloudinary.com/dq96gflxv/image/upload/v1789196573/VISION-Y/faculty/profilepic02396.jpg",
  "/images/faculty/profilepic02696.png": "https://res.cloudinary.com/dq96gflxv/image/upload/v1789196574/VISION-Y/faculty/profilepic02696.png",
  "/images/faculty/profilepic03082.JPG": "https://res.cloudinary.com/dq96gflxv/image/upload/v1789196575/VISION-Y/faculty/profilepic03082.jpg",
  "/images/faculty/profilepic03082.jpg": "https://res.cloudinary.com/dq96gflxv/image/upload/v1789196575/VISION-Y/faculty/profilepic03082.jpg",
  "/images/faculty/profilepic163.jpg": "https://res.cloudinary.com/dq96gflxv/image/upload/v1789196577/VISION-Y/faculty/profilepic163.jpg",
  "/images/faculty/profilepic646.png": "https://res.cloudinary.com/dq96gflxv/image/upload/v1789196578/VISION-Y/faculty/profilepic646.png",
  "/images/faculty/profilepic675.webp": "https://res.cloudinary.com/dq96gflxv/image/upload/v1789196579/VISION-Y/faculty/profilepic675.webp",
  "/images/faculty/profilepic689.webp": "https://res.cloudinary.com/dq96gflxv/image/upload/v1789196580/VISION-Y/faculty/profilepic689.webp",
  "/images/faculty/pushya.jpg": "https://res.cloudinary.com/dq96gflxv/image/upload/v1789196580/VISION-Y/faculty/pushya.jpg",
  "/images/faculty/satish.jpg": "https://res.cloudinary.com/dq96gflxv/image/upload/v1789196581/VISION-Y/faculty/satish.jpg",
  "/images/faculty/senthil.jpg": "https://res.cloudinary.com/dq96gflxv/image/upload/v1789196583/VISION-Y/faculty/senthil.jpg",
  "/images/faculty/spandana.jpg": "https://res.cloudinary.com/dq96gflxv/image/upload/v1789196584/VISION-Y/faculty/spandana.jpg",
  "/images/faculty/veeranjaneyulu.jpg": "https://res.cloudinary.com/dq96gflxv/image/upload/v1789196584/VISION-Y/faculty/veeranjaneyulu.jpg",
  "/images/login-campus.png": "https://res.cloudinary.com/dq96gflxv/image/upload/v1789196585/VISION-Y/branding/login-campus.jpg",
  "/images/login-policy-bot.png": "https://res.cloudinary.com/dq96gflxv/image/upload/v1789196586/VISION-Y/branding/login-policy-bot.jpg",
  "/images/staff/profilepic01203.png": "https://res.cloudinary.com/dq96gflxv/image/upload/v1789196587/VISION-Y/staff/profilepic01203.png",
  "/images/staff/profilepic01447.jpg": "https://res.cloudinary.com/dq96gflxv/image/upload/v1789196588/VISION-Y/staff/profilepic01447.jpg",
  "/images/staff/profilepic01885.jpg": "https://res.cloudinary.com/dq96gflxv/image/upload/v1789196589/VISION-Y/staff/profilepic01885.jpg",
  "/images/staff/profilepic02339.jpeg": "https://res.cloudinary.com/dq96gflxv/image/upload/v1789196590/VISION-Y/staff/profilepic02339.jpg",
  "/images/staff/profilepic02346.jpeg": "https://res.cloudinary.com/dq96gflxv/image/upload/v1789196591/VISION-Y/staff/profilepic02346.jpg",
  "/images/staff/profilepic02490.JPG": "https://res.cloudinary.com/dq96gflxv/image/upload/v1789196592/VISION-Y/staff/profilepic02490.jpg",
  "/images/staff/profilepic02490.jpg": "https://res.cloudinary.com/dq96gflxv/image/upload/v1789196592/VISION-Y/staff/profilepic02490.jpg",
  "/images/staff/profilepic03054.JPG": "https://res.cloudinary.com/dq96gflxv/image/upload/v1789196593/VISION-Y/staff/profilepic03054.jpg",
  "/images/staff/profilepic03054.jpg": "https://res.cloudinary.com/dq96gflxv/image/upload/v1789196593/VISION-Y/staff/profilepic03054.jpg",
  "/images/staff/profilepic30104.jpeg": "https://res.cloudinary.com/dq96gflxv/image/upload/v1789196594/VISION-Y/staff/profilepic30104.jpg",
  "/images/staff/profilepic40018.jpg": "https://res.cloudinary.com/dq96gflxv/image/upload/v1789196595/VISION-Y/staff/profilepic40018.jpg",
  "/images/staff/profilepic40019.jpeg": "https://res.cloudinary.com/dq96gflxv/image/upload/v1789196598/VISION-Y/staff/profilepic40019.jpg",
  "/images/students/anvi.svg": "https://res.cloudinary.com/dq96gflxv/image/upload/v1789196599/VISION-Y/avatars/placeholders/anvi.svg",
  "/images/students/arya.svg": "https://res.cloudinary.com/dq96gflxv/image/upload/v1789196600/VISION-Y/avatars/placeholders/arya.svg",
  "/images/students/dev.svg": "https://res.cloudinary.com/dq96gflxv/image/upload/v1789196602/VISION-Y/avatars/placeholders/dev.svg",
  "/images/students/isha.svg": "https://res.cloudinary.com/dq96gflxv/image/upload/v1789196603/VISION-Y/avatars/placeholders/isha.svg",
  "/images/students/kabir.svg": "https://res.cloudinary.com/dq96gflxv/image/upload/v1789196605/VISION-Y/avatars/placeholders/kabir.svg",
  "/images/students/kiara.svg": "https://res.cloudinary.com/dq96gflxv/image/upload/v1789196607/VISION-Y/avatars/placeholders/kiara.svg",
  "/images/students/mira.svg": "https://res.cloudinary.com/dq96gflxv/image/upload/v1789196608/VISION-Y/avatars/placeholders/mira.svg",
  "/images/students/nisha.svg": "https://res.cloudinary.com/dq96gflxv/image/upload/v1789196610/VISION-Y/avatars/placeholders/nisha.svg",
  "/images/students/rohan.svg": "https://res.cloudinary.com/dq96gflxv/image/upload/v1789196612/VISION-Y/avatars/placeholders/rohan.svg",
  "/images/students/yash.svg": "https://res.cloudinary.com/dq96gflxv/image/upload/v1789196614/VISION-Y/avatars/placeholders/yash.svg",
  "/images/vignan-logo.png": "https://res.cloudinary.com/dq96gflxv/image/upload/v1789196616/VISION-Y/branding/vignan-logo.png",
  "/images/Vignan_logo.png": "https://res.cloudinary.com/dq96gflxv/image/upload/v1789196617/VISION-Y/branding/Vignan_logo.png"
};

/** Resolve a local /images/... path to Cloudinary HTTPS URL (falls back to local). */
export function cloudMedia(localPath: string | null | undefined): string | null {
  if (!localPath) return null;
  if (/^https?:\/\//i.test(localPath)) return localPath;
  const key = localPath.startsWith("/") ? localPath : `/${localPath}`;
  return (
    CLOUD_MEDIA[key] ??
    CLOUD_MEDIA[key.replace(/\.JPG$/i, ".jpg")] ??
    CLOUD_MEDIA[key.replace(/\.JPEG$/i, ".jpeg")] ??
    CLOUD_MEDIA[key.replace(/\.PNG$/i, ".png")] ??
    localPath
  );
}

/** Remap any /images avatar still on disk paths after Cloudinary sync. */
export function remapUserAvatars(
  users: Iterable<{ avatar_url: string | null }>,
): number {
  let n = 0;
  for (const u of users) {
    if (!u.avatar_url || u.avatar_url.startsWith("http")) continue;
    const next = cloudMedia(u.avatar_url);
    if (next && next !== u.avatar_url) {
      u.avatar_url = next;
      n += 1;
    }
  }
  return n;
}
