/**
 * AUTO-GENERATED by scripts/syncCloudinaryMedia.ts — do not edit by hand.
 * Re-run: npm run sync:media --prefix backend
 */
export const CLOUD_MEDIA: Record<string, string> = {};

/** Resolve a local /images/... path to Cloudinary HTTPS URL (falls back to local). */
export function cloudMedia(localPath: string | null | undefined): string | null {
  if (!localPath) return null;
  if (/^https?:\/\//i.test(localPath)) return localPath;
  return CLOUD_MEDIA[localPath] ?? localPath;
}
