/**
 * Upload frontend/public/images → Cloudinary in a structured tree:
 *
 *   vision-y/branding/...
 *   vision-y/students/...
 *   vision-y/faculty/...
 *   vision-y/staff/...
 *   vision-y/avatars/...   (misc avatar assets)
 *
 * Writes backend/src/media/cloudMedia.ts with the URL map.
 *
 * Usage: npx tsx scripts/syncCloudinaryMedia.ts
 */
import dotenv from "dotenv";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { v2 as cloudinary } from "cloudinary";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, "../..");
dotenv.config({ path: path.join(__dirname, "../.env") });

const imagesRoot = path.join(root, "frontend/public/images");
const outFile = path.join(__dirname, "../src/media/cloudMedia.ts");

const cloud = (process.env.CLOUDINARY_CLOUD_NAME ?? "").trim().toLowerCase();
const key = process.env.CLOUDINARY_API_KEY;
const secret = process.env.CLOUDINARY_API_SECRET;

if (!cloud || !key || !secret) {
  console.error("Missing CLOUDINARY_* env vars in backend/.env");
  process.exit(1);
}

cloudinary.config({ cloud_name: cloud, api_key: key, api_secret: secret, secure: true });

const IMAGE_EXT = new Set([".png", ".jpg", ".jpeg", ".webp", ".gif", ".svg"]);

function walk(dir: string): string[] {
  const out: string[] = [];
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) out.push(...walk(full));
    else if (IMAGE_EXT.has(path.extname(entry.name).toLowerCase())) out.push(full);
  }
  return out;
}

/** Map local relative path under /images to Cloudinary folder + public_id */
function cloudTarget(relPosix: string): { folder: string; public_id: string } {
  const parts = relPosix.split("/");
  const file = parts[parts.length - 1];
  const base = file.replace(/\.[^.]+$/, "").replace(/[^a-zA-Z0-9_-]/g, "_");

  if (parts[0] === "avatars" && parts[1] === "students") {
    return { folder: "VISION-Y/students", public_id: base };
  }
  if (parts[0] === "faculty") {
    return { folder: "VISION-Y/faculty", public_id: base };
  }
  if (parts[0] === "staff") {
    return { folder: "VISION-Y/staff", public_id: base };
  }
  if (parts[0] === "students") {
    return { folder: "VISION-Y/avatars/placeholders", public_id: base };
  }
  if (parts[0] === "avatars") {
    return { folder: "VISION-Y/avatars/placeholders", public_id: base };
  }
  // branding / root images
  return { folder: "VISION-Y/branding", public_id: base };
}

async function uploadOne(abs: string): Promise<{ local: string; url: string }> {
  const rel = path.relative(imagesRoot, abs).split(path.sep).join("/");
  const local = `/images/${rel}`;
  const { folder, public_id } = cloudTarget(rel);

  const result = await cloudinary.uploader.upload(abs, {
    folder,
    public_id,
    overwrite: true,
    resource_type: "image",
  });

  console.log(`✓ ${local} → ${folder}/${public_id}`);
  return { local, url: result.secure_url };
}

async function main() {
  if (!fs.existsSync(imagesRoot)) {
    console.error("Missing", imagesRoot);
    process.exit(1);
  }

  const files = walk(imagesRoot);
  console.log(`Uploading ${files.length} images to cloud "${cloud}"…`);

  const map: Record<string, string> = {};
  for (const file of files) {
    try {
      const { local, url } = await uploadOne(file);
      map[local] = url;
      // case-insensitive aliases for .JPG vs .jpg in seed
      map[local.replace(/\.JPG$/i, ".jpg")] = url;
      map[local.replace(/\.JPEG$/i, ".jpeg")] = url;
      map[local.replace(/\.PNG$/i, ".png")] = url;
    } catch (err) {
      console.error(`✗ ${file}`, err instanceof Error ? err.message : err);
    }
  }

  fs.mkdirSync(path.dirname(outFile), { recursive: true });
  const body = `/**
 * AUTO-GENERATED by scripts/syncCloudinaryMedia.ts — do not edit by hand.
 * Re-run: npm run sync:media --prefix backend
 */
export const CLOUD_MEDIA: Record<string, string> = ${JSON.stringify(map, null, 2)};

/** Resolve a local /images/... path to Cloudinary HTTPS URL (falls back to local). */
export function cloudMedia(localPath: string | null | undefined): string | null {
  if (!localPath) return null;
  if (/^https?:\\/\\//i.test(localPath)) return localPath;
  const key = localPath.startsWith("/") ? localPath : \`/\${localPath}\`;
  return (
    CLOUD_MEDIA[key] ??
    CLOUD_MEDIA[key.replace(/\\.JPG$/i, ".jpg")] ??
    CLOUD_MEDIA[key.replace(/\\.JPEG$/i, ".jpeg")] ??
    CLOUD_MEDIA[key.replace(/\\.PNG$/i, ".png")] ??
    localPath
  );
}
`;
  fs.writeFileSync(outFile, body, "utf8");
  console.log(`\nWrote ${Object.keys(map).length} entries → ${outFile}`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
